import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import {useState,useEffect} from 'react'
import Link from 'next/link'

export default function Home({movies}) {
  const[imgnumber,setImgnumber]=useState(4)
  const [numbers,setNumbers]=useState(0)
  useEffect(()=>{
    if(imgnumber>4){
      setImgnumber(1)
      }
      if(imgnumber<0){
        setImgnumber(1)
        }
  },[imgnumber])

  useEffect(()=>{
var num=[]
for(let i=0;i<1000;i++){
  num.push(i)
}
setNumbers(num)

  },[])
  return (
    <div className={styles.container}>
      {imgnumber}
    
      
      <Head>
        <title>Bookmyshow clone With Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className={styles.imagelinks}>
  <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-movies-collection-202201201113.png'
  alt=''  width='60'/>
  
  <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-stream-collection-202201201113.png'
  alt=''  width='60'/>
  
  <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-music-shows-collection-202201201113.png'
  alt=''  width='60'/>
  
  <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-comedy-shows-collection-202201201113.png'
  alt=''  width='60'/>
  <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-adventure-collection-202201201113.png'
  alt='' width='60'/>
    <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-plays-collection-202201201113.png'
  alt='' width='60'/>
    <img src='https://assets-in.bmscdn.com/discovery-catalog/collections/tr:w-800,h-800:w-300:q-80/icd-plays-collection-202201201113.png'
  alt='' width='60'/>
</div>
<div className={styles.scrollimageslinks}>
<div className={styles.leftarrow}>left</div>
  <div className={styles.rightarrow}>right</div>
<div className={imgnumber===1?styles.seeimage:styles.scrollimage}>
 <img src='https://assets-in.bmscdn.com/promotions/cms/creatives/1651468547404_sunburnapp.jpg'
 alt='' width='500'/>
 </div>
 <div className={imgnumber===2?styles.seeimage:styles.scrollimage}>
<img src='https://assets-in.bmscdn.com/promotions/cms/creatives/1651216452418_app_630x315.jpg' 
alt='' width='500'/>
</div>
<div className={imgnumber===3?styles.seeimage:styles.scrollimage}>
<img src='https://assets-in.bmscdn.com/promotions/cms/creatives/1651221220328_offerapp.jpg'
alt='' width='500'/>
</div>
<div className={imgnumber===4?styles.seeimage:styles.scrollimage}>
<img src='https://assets-in.bmscdn.com/promotions/cms/creatives/1651492456712_restaurantapp.jpg'
alt='' width='500'/>
</div>
</div>
<div className={styles.movieimagelinks}>
  {movies?.map((m,index)=> <div className={styles.movieimagelink}>
<Link href={`/movie/${m._id}`}>
<img src={m.image_url} alt='' width='60'/>
  </Link>
  {m.name}

  </div>)}
</div>
    </div>
  )
}


export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/movies')
  const json = await res.json()
  console.log(json)
  return {
    props: {
      movies: json.data,
    },
  }
}
