import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import {useState,useEffect} from 'react'
import Link from 'next/link'

export default function Navbar({ children }) {
    return (

    <div className={styles.container}>
  
    
    <Head>
      <title>Bookmyshow clone With Next</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  <div className={styles.navbar}>
    <div className={styles.firstdiv}>
<h5>book my show</h5>
<input placeholder='Search for Movies,Places,Events,Play,Sports and Activities'/>
    </div>
    <div className={styles.seconddiv}>
<h5>Bengaluru</h5>
<Link href='/login'>
<button className={styles.signinbtn}>Sign in</button>
</Link>
<h5>Menu</h5>
    </div>
  </div>
  <div className={styles.bottomnavbar}>
    <div className={styles.firstdivbottom}>
<li>Movies</li>
<li>Streams</li>
<li>Events</li>
<li>Plays</li>
<li>Sports</li>
<li>Activities</li>
<li>Buzz</li>
    </div>
    <div className={styles.seconddivbottom}>
    <li>Bookmyshow</li>
<li>Corporate</li>
<li>Offers</li>
<li>Gift Cards</li>
    </div>
    </div>
    </div>
    )
    }